# Generated by Django 4.2.7 on 2024-05-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=120)),
                ("last_name", models.CharField(max_length=120)),
            ],
            options={
                "verbose_name": "Doctor",
                "verbose_name_plural": "Doctors",
                "ordering": ("id",),
            },
        ),
    ]
